### ISSUE TITLE
World bug

### ISSUE THREAD

**Issue by DRNUMBER1** [Phoenix616/RandomTeleport#43]
#### Plugin Version
FUBS Random Teleport 2.0 Pre-Release (b71)
 
#### Config
```yaml
# Default language to use when client's language isn't available
lang: en
# Some debug information
debug: true
# Delay in ticks between checking chunks when searching

# Blocks to teleport on in normal mode
save-blocks:
- sand
- sandstone
- gravel
- dirt
- grass_block
- coarse_dirt
- podzol
- stone
- granite
- diorite
- andesite
- cobblestone
- end_stone
- netherrack

# Blocks unsave when in "--force blocks" mode
unsave-blocks:
- air
- water
- lava
- oak_sapling
- spruce_sapling
- birch_sapling
- jungle_sapling
- acacia_sapling
- dark_oak_sapling
- white_bed
- orange_bed
- magenta_bed
- light_blue_bed
- yellow_bed
- lime_bed
- pink_bed
- gray_bed
- light_gray_bed
- cyan_bed
- purple_bed
- blue_bed
- brown_bed
- green_bed
- red_bed
- black_bed
- powered_rail
- detector_rail
- cobweb
- piston_head
- tnt
- torch
- fire
- sign
- ladder
- rail
- wall_sign
- lever
- stone_pressure_plate
- iron_door
- redstone_wall_torch
- redstone_torch
- stone_button
- cactus
- magma_block
- nether_portal
- vine
- end_portal
- end_portal_frame
- tripwire_hook
- tripwire
- flower_pot
- oak_leaves
- spruce_leaves
- birch_leaves
- jungle_leaves
- acacia_leaves
- dark_oak_leaves
- barrier
- iron_trapdoor
- oak_trapdoor
- spruce_trapdoor
- birch_trapdoor
- jungle_trapdoor
- acacia_trapdoor
- dark_oak_trapdoor
- oak_door
- spruce_door
- birch_door
- jungle_door
- acacia_door
- dark_oak_door
- end_rod
- end_gateway

sign-variables:
- "[RTP]"
- "[RandomTP]"

# Just write your command arguments as you would use it ingame behind /rtp
# Don't use the -p parameter, this will get added automatically with the senders name/the specified playername
presets:
  # Triggered when you use /rtp without any additional paramters
  default: "100 1000"
  # add more to use /rtp <rtpname>, player needs "randomteleport.presets.<rtpname>"
  #   <rtpname>: "/rtp 1 2"
  test: "10 200 -f"
  wild: "100 800 -w SMPP"
```

#### Environment description
This server is running Paper version git-Paper-406 (MC: 1.16.4) (Implementing API version 1.16.4-R0.1-SNAPSHOT)
 
 
#### Full Log

```
31.01 23:57:00 [Server] ERROR Error while parsing preset wild
31.01 23:57:00 [Server] INFO de.themoep.randomteleport.searcher.options.WorldNotFoundException: SMPP was not found!
31.01 23:57:00 [Server] INFO at de.themoep.randomteleport.RandomTeleport.lambda$initOptionParsers$9(RandomTeleport.java:171) ~[?:?]
31.01 23:57:00 [Server] INFO at de.themoep.randomteleport.searcher.options.SimpleOptionParser.parse(SimpleOptionParser.java:76) ~[?:?]
31.01 23:57:00 [Server] INFO at de.themoep.randomteleport.RandomTeleport.parseAndRun(RandomTeleport.java:347) ~[?:?]
31.01 23:57:00 [Server] INFO at de.themoep.randomteleport.RandomTeleport.runPreset(RandomTeleport.java:442) ~[?:?]
31.01 23:57:00 [Server] INFO at de.themoep.randomteleport.listeners.SignListener.onSignClick(SignListener.java:94) ~[?:?]
31.01 23:57:00 [Server] INFO at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor227.execute(Unknown Source) ~[?:?]
31.01 23:57:00 [Server] INFO at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[patched_1.16.4.jar:git-Paper-406]
31.01 23:57:00 [Server] INFO at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[patched_1.16.4.jar:git-Paper-406]
31.01 23:57:00 [Server] INFO at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.16.4.jar:git-Paper-406]
31.01 23:57:00 [Server] INFO at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:607) ~[patched_1.16.4.jar:git-Paper-406]
31.01 23:57:00 [Server] INFO at org.bukkit.craftbukkit.v1_16_R3.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:510) ~[patched_1.16.4.jar:git-Paper-406]
31.01 23:57:00 [Server] INFO at net.minecraft.server.v1_16_R3.PlayerInteractManager.a(PlayerInteractManager.java:464) ~[patched_1.16.4.jar:git-Paper-406]
31.01 23:57:00 [Server] INFO at net.minecraft.server.v1_16_R3.PlayerConnection.a(PlayerConnection.java:1549) ~[patched_1.16.4.jar:git-Paper-406]
31.01 23:57:00 [Server] INFO at net.minecraft.server.v1_16_R3.PacketPlayInUseItem.a(PacketPlayInUseItem.java:27) ~[patched_1.16.4.jar:git-Paper-406]
31.01 23:57:00 [Server] INFO at net.minecraft.server.v1_16_R3.PacketPlayInUseItem.a(PacketPlayInUseItem.java:5) ~[patched_1.16.4.jar:git-Paper-406]
31.01 23:57:00 [Server] INFO at net.minecraft.server.v1_16_R3.PlayerConnectionUtils.lambda$ensureMainThread$1(PlayerConnectionUtils.java:23) ~[patched_1.16.4.jar:git-Paper-406]
31.01 23:57:00 [Server] INFO at net.minecraft.server.v1_16_R3.TickTask.run(SourceFile:18) ~[patched_1.16.4.jar:git-Paper-406]
31.01 23:57:00 [Server] INFO at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:136) ~[patched_1.16.4.jar:git-Paper-406]
31.01 23:57:00 [Server] INFO at net.minecraft.server.v1_16_R3.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) ~[patched_1.16.4.jar:git-Paper-406]
31.01 23:57:00 [Server] INFO at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:109) ~[patched_1.16.4.jar:git-Paper-406]
31.01 23:57:00 [Server] INFO at net.minecraft.server.v1_16_R3.MinecraftServer.bb(MinecraftServer.java:1128) ~[patched_1.16.4.jar:git-Paper-406]
31.01 23:57:00 [Server] INFO at net.minecraft.server.v1_16_R3.MinecraftServer.executeNext(MinecraftServer.java:1121) ~[patched_1.16.4.jar:git-Paper-406]
31.01 23:57:00 [Server] INFO at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.executeAll(IAsyncTaskHandler.java:95) ~[patched_1.16.4.jar:git-Paper-406]
31.01 23:57:00 [Server] INFO at net.minecraft.server.v1_16_R3.MinecraftServer.a(MinecraftServer.java:1257) ~[patched_1.16.4.jar:git-Paper-406]
31.01 23:57:00 [Server] INFO at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:992) ~[patched_1.16.4.jar:git-Paper-406]
31.01 23:57:00 [Server] INFO at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:173) ~[patched_1.16.4.jar:git-Paper-406]
31.01 23:57:00 [Server] INFO at java.lang.Thread.run(Thread.java:834) [?:?]
```

#### What other programs/plugins are you running?

many

#### What is happening?

it cannot find the world even tho the server has the world in the files

#### What did you expect to happen?

tpping us to a diffrent world

#### Additional context

nope
